name: ShivamCI/CD

on:
 workflow_dispatch:
 push:
  branches:
   - main
 
jobs:
 ShivamJob:
  runs-on: ubuntu-latest
  
  steps:
   - name: checkout on branch
     uses: actions/checkout@v3
     
   - name: Open first file
     run: cat *.txt
 
