name: selenium build

on:
 workflow_dispatch:
 push:
  branches:
   - feature/Selenium
   
jobs:
  Selenium_test:
   runs-on: ubuntu-latest
   
   steps:
    - name: checkout coder
      uses: actions/checkout@v3
      
    - name: setup-java
      uses: actions/setup-java@v3
      
    - name: run selenium test
      run: mvn test
   
   
